### ISSUE TITLE
SPM Integration

### ISSUE THREAD

**Issue by delannoyk** [Iterable/iterable-swift-sdk#678]
Hi Iterable team,

We're in the process of integrating your SDK in our app using SPM and unfortunately, we can't. The reason is that the name of this repository is `swift-sdk` and one of our other dependencies is also using `swift-sdk`.

> dependency on 'https://github.com/iterable/swift-sdk' conflicts with dependency on 'https://github.com/optimizely/swift-sdk' which has the same identity 'swift-sdk'

After digging a little bit, I found that I was not the only one having this issue (thread [here](https://forums.swift.org/t/two-third-party-packages-share-the-same-name/60721))

According to official SPM team members:
> SwiftPM uses the last path component of URL as the "identity";

I tried using `SSH` instead of `https` but it didn't help.

**Comment by esscosejo** [comment]
Hi Iterable team,

Our team was experienced the same situation @delannoyk described here. Thanks to this issue and the one created in the Optimizely repo, their team did a fix and we are able to make it work.

But this is could still be an issue for other devs and teams.  Here is the Optimizely fix that could be applied here too.

https://github.com/optimizely/swift-sdk/issues/520#issuecomment-1771776504

Best Regards.

**Comment by Ayyanchira** [comment]
Hi @delannoyk and @esscosejo ! Thank you for the references.
We have renamed our repo to `iterable-swift-sdk` to avoid possible collision. The previous name also works as a alias. 
Please let us know if it works out for your projects. 

Thanks and Regards

**Comment by delannoyk** [comment]
Thanks @Ayyanchira

**Comment by esscosejo** [comment]
Thanks a lot.

—
Carlos Osejo
Extra Space Storage
iOS Engineer



On Oct 2, 2024, at 3:33 PM, Kevin Delannoy ***@***.***> wrote:

CAUTION: External email. THINK before you click!


Thanks @Ayyanchira<https://urldefense.com/v3/__https://github.com/Ayyanchira__;!!EDpRQbZV1DQ!x0DuJtDxRYRKFa5b8Pxx-I7CMWZWZjmCvsEYwfF_oRXerbzRsc5UeULzVlu9tVd1TTN2_fFhJkIB1yMA9QQW5YnXSA$>
