### ISSUE TITLE
Xcode 16.1 Beta2 shows error in Iterable SDK stating Protocol 'WKNavigationDelegate' requires 'webView(_:decidePolicyFor:preferences:decisionHandler:)' to be available in iOS 12.0 and newer

### ISSUE THREAD

**Issue by harish-suthar** [Iterable/iterable-swift-sdk#826]
Xcode 16.1 Beta2 shows error in Iterable SDK when trying to run the project, please refer below screenshot.

> Protocol 'WKNavigationDelegate' requires 'webView(_:decidePolicyFor:preferences:decisionHandler:)' to be available in iOS 12.0 and newer

<img width="1713" alt="Screenshot 2024-09-18 at 10 24 56 AM" src="https://github.com/user-attachments/assets/6b9319ef-bffe-4d94-bb08-0a452143cae3">

**Comment by Ayyanchira** [comment]
Hi @harish-suthar, Which version of Iterable Swift SDK is used in the project?

**Comment by harish-suthar** [comment]
> Hi @harish-suthar, Which version of Iterable Swift SDK is used in the project?

@Ayyanchira I am using `6.5.7` the latest one https://github.com/Iterable/swift-sdk/releases/tag/6.5.7

**Comment by ignaspaladinas** [comment]
Same issue here.

**Comment by joaodordio** [comment]
Hey @harish-suthar, Apple just [released](https://developer.apple.com/go/?id=xcode-16_1-sdk-rn) the Xcode 16 beta 3, and from my tests it looks like it's no longer complaining about this. Probably a flaky build error.

Are you able to confirm this please?

**Comment by harish-suthar** [comment]
@joaodordio Yes its working fine on Xcode 16 beta 3, thanks for notifying. We shall close this issue now.
